version: '2'
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - graphite
  graphite:
    image: hopsoft/graphite-statsd
    restart: always
    ports:
      - "5000:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
